server:
  port: 8000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/validol
    username: postgres
    password: 1111
  jpa:
    show-sql: on
    generate-ddl: on
    hibernate:
      ddl-auto: update
